

-- ----------------------------
-- SYS_USER表索引
-- ----------------------------
--DROP INDEX IDX_SYS_USER_USER_NO ON SYS_USER;
--DROP INDEX IDX_SYS_USER_LOGIN_NAME ON SYS_USER;

CREATE INDEX IDX_SYS_USER_USER_NO ON SYS_USER(USER_NO); 
CREATE UNIQUE INDEX IDX_SYS_USER_LOGIN_NAME ON SYS_USER(LOGIN_NAME); 


-- ----------------------------
-- SYS_AREA表索引
-- ----------------------------
--DROP INDEX IDX_SYS_AREA_AREACODE ON SYS_AREA;

CREATE INDEX IDX_SYS_AREA_AREACODE ON SYS_AREA(AREA_CODE); 


-- ----------------------------
-- SYS_DICT表索引
-- SYS_DICT_DETAIL表索引
-- ----------------------------
--DROP INDEX IDX_SYS_DICT_DICT_CODE ON SYS_DICT;
--DROP INDEX IDX_SYS_DICT_DETAIL_DICTID ON SYS_DICT_DETAIL;
-- DROP INDEX IDX_SYS_DICT_DETAIL_DDVALUE ON SYS_DICT_DETAIL;

CREATE INDEX IDX_SYS_DICT_DICT_CODE ON SYS_DICT(DICT_CODE); 
CREATE INDEX IDX_SYS_DICT_DETAIL_DICTID ON SYS_DICT_DETAIL(DICT_ID); 
-- CREATE INDEX IDX_SYS_DICT_DETAIL_DDVALUE ON SYS_DICT_DETAIL(DICT_ID, DICT_DETAIL_VALUE); 


-- ----------------------------
-- SYS_ORG表索引
-- ----------------------------
--DROP INDEX IDX_SYS_ORG_ORG_CODE ON SYS_ORG;

CREATE INDEX IDX_SYS_ORG_ORG_CODE ON SYS_ORG(ORG_CODE); 


-- ----------------------------
-- SYS_ORG_USER表索引
-- ----------------------------
--DROP INDEX IDX_SYS_ORG_USER_ORG_ID ON SYS_ORG_USER;
--DROP INDEX IDX_SYS_ORG_USER_USER_ID ON SYS_ORG_USER;

CREATE INDEX IDX_SYS_ORG_USER_ORG_ID ON SYS_ORG_USER(ORG_ID); 
CREATE INDEX IDX_SYS_ORG_USER_USER_ID ON SYS_ORG_USER(USER_ID); 


-- ----------------------------
-- SYS_PRV_TABLE_DEF表索引
-- ----------------------------
--DROP INDEX UNI_SYS_DATA_PRV_TABLE ON SYS_PRV_TABLE_DEF;

CREATE UNIQUE INDEX UNI_SYS_DATA_PRV_TABLE ON SYS_PRV_TABLE_DEF(TABLE_NAME); 


-- ----------------------------
-- SYS_USER_MSG_RELATION表索引
-- ----------------------------
--DROP INDEX IDX_SYS_USER_MP_UID ON SYS_USER_MSG_RELATION;

CREATE INDEX IDX_SYS_USER_MP_UID ON SYS_USER_MSG_RELATION(USER_ID); 




-- ----------------------------
-- VMTREE_INFO表索引
-- ----------------------------
--DROP INDEX IDX_VMTREE_INFO_ORG_ID ON VMTREE_INFO;
--DROP INDEX IDX_VMTREE_INFO_PARENT_ID ON VMTREE_INFO;

CREATE INDEX IDX_VMTREE_INFO_ORG_ID ON VMTREE_INFO(ORG_ID); 
CREATE INDEX IDX_VMTREE_INFO_PARENT_ID ON VMTREE_INFO(PARENT_ID); 


-- ----------------------------
-- VMUSER_VMORG_MAP表索引
-- ----------------------------
--DROP INDEX IDX_VMUSER_VMORG_MAP_ORG_ID ON VMUSER_VMORG_MAP;
--DROP INDEX IDX_VMUSER_VMORG_MAP_USER_ID ON VMUSER_VMORG_MAP;

CREATE INDEX IDX_VMUSER_VMORG_MAP_ORG_ID ON VMUSER_VMORG_MAP(ORG_ID); 
CREATE UNIQUE INDEX IDX_VMUSER_VMORG_MAP_USER_ID ON VMUSER_VMORG_MAP(USER_ID, ORG_TYPE); 







